### ISSUE TITLE
klData.data should be initialized with {}, else next line will throw error

### ISSUE THREAD

**Issue by justinunilever** [klaviyo/SFCC_Klaviyo#14]
https://github.com/klaviyo/SFCC_Klaviyo/blob/67764a60e47a01d6591688405cef3e0bb93e169e/cartridges/int_klaviyo_sfra/cartridge/scripts/utils/klaviyo/klaviyoDataLayer.js#L23-L24
 this should be:
    klData.data = {};
    klData.data.debug_error = '';

**Comment by cykolln** [comment]
This has been fixed in the new cartridge versions
